blog_store/urls.py
from django.urls import path
from blog_store.views import (
    BlogCreateView,
    BlogListView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
    activity,
)

app_name = "blog_store"

urlpatterns = [
    path("blog_create", BlogCreateView.as_view(), name="blogpost_form"),
    path("blogs", BlogListView.as_view(), name="blogpost_list"),
    path(
        "blogs/<int:pk>-<slug:slug>", BlogDetailView.as_view(), name="blogpost_detail"
    ),
    path(
        "blog_update/<int:pk>-<slug:slug>",
        BlogUpdateView.as_view(),
        name="blogpost_form",
    ),
    path(
        "delete_blog/<int:pk>-<slug:slug>",
        BlogDeleteView.as_view(),
        name="blogpost_delete",
    ),
    path("blogs/activity/<int:pk>-<slug:slug>", activity, name="blogpost_activity"),
]


# другие urlpatterns

categories/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from categories.apps import CategoriesConfig  # Импорт для формирования ключа

from .views import (
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
)

app_name = CategoriesConfig.name

urlpatterns = [
    path("", ProductListView.as_view(), name="product_store"),  # Список продуктов
    path(
        "contact/", ProductCreateView.as_view(), name="product_form"
    ),  # Форма создания продукта
    path(
        "product_store/product_detail/<int:pk>/",
        cache_page(60)(ProductDetailView.as_view()),
        name="product_detail",
    ),
    path(
        "product_store/product_update/<int:pk>/",
        ProductUpdateView.as_view(),
        name="update_forms",
    ),  # Обновление продукта
]

online_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("categories.urls", namespace="categories")),
    path("blog_store/", include("blog_store.urls", namespace="blog_store")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView, PasswordResetDoneView, PasswordResetConfirmView
from django.views.generic import TemplateView

from users.apps import UsersConfig
from users.views import RegisterUser, VerifyEmailView, password_reset_view

app_name = UsersConfig.name





urlpatterns = [
    path("logout/", LogoutView.as_view(), name="logout"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("register/", RegisterUser.as_view(), name="register"),
    path('verify_email/<str:token>/', VerifyEmailView.as_view(), name='verify_email'),
    path('email_verified/', TemplateView.as_view(template_name='users/email_verified.html'), name='email_verified'),
    path('invalid_token/', TemplateView.as_view(template_name='users/invalid_token.html'), name='invalid_token'),
    path('register/message_post/', TemplateView.as_view(template_name='users/message_post.html'), name='message_post'),
    path('login/password_reset/', password_reset_view, name='password_reset')
]

categories/models/category.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"

categories/models/product.py
from django.db import models
from users.models import User

# Create your models here.
NULLABLE = {"blank": True, "null": True}  # делает не обязательным
# заполнения поля
# если не заполнить
# то оно является обязательным для заполнения


# формирует в бд таблицы
class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="Наименование")  # Наименование
    description = models.TextField(verbose_name="Описание")  # Описание
    image_product = models.ImageField(
        verbose_name="Изображение товара",
        upload_to="image_product/",
        name="image_product",
        **NULLABLE
    )  # Изображение

    category = models.ForeignKey(
        "Category", on_delete=models.CASCADE, verbose_name="Категории спорта"
    )  # Категория здесь идёт связь
    # таблиц
    # Продуктов и категории
    price_per_purchase = models.IntegerField(
        verbose_name="Устанока цены"
    )  # Цена за покупку
    date_of_creation = models.DateTimeField(
        auto_now_add=True
    )  # Дата создания (записи в БД)
    date_of_last_change = models.DateTimeField(
        auto_now=True
    )  # Дата последнего изменения (записи в БД)
    # manufactured_at = models.DateField()  # Дата производства продукта

    author = models.ForeignKey(User, on_delete=models.SET_NULL, **NULLABLE)
    is_published = models.BooleanField(
        default=False, verbose_name="признак публиукации"
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"
        permissions = [
            ("can_change_product_categories", "Может изменять название Категории"),
            ("can_set_product_published", "Может изменять статус публикации"),
            ("can_change_description", "может менять описание любого продукта"),
        ]

categories/models/version.py
from django.db import models


class Version(models.Model):

    product = models.ForeignKey(
        "Product", on_delete=models.CASCADE, related_name="versions"
    )
    number_version = models.CharField(max_length=100, verbose_name="номер версии")
    name_version = models.CharField(max_length=100, verbose_name="название версии")
    is_current_version = models.BooleanField(
        default=False, verbose_name="Признак текущей версии"
    )

    def __str__(self):
        return f"{self.name_version}, {self.number_version}"

    class Meta:
        verbose_name = "версия продукта"
        verbose_name_plural = "версии продуктов"

categories/forms.py
from django import forms
from categories.models.product import Product
from categories.models.version import Version
from categories.list_config_name.config_name import FORBIDDEN_WORDS


class BootstrapForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({"class": "form-control"})


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "name",
            "description",
            "image_product",
            "category",
            "price_per_purchase",
            "is_published",
        ]

    def clean_name(self):
        name = self.cleaned_data["name"].lower()
        for forbidden_word in FORBIDDEN_WORDS:
            if forbidden_word in name:
                raise forms.ValidationError("Пожалуйста, измените название.")
        return name


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ["product", "name_version", "number_version", "is_current_version"]

    def clean(self):
        cleaned_data = super().clean()
        is_active = cleaned_data.get("is_current_version")
        if is_active and self.instance.product:
            Version.objects.filter(
                product=self.instance.product, is_current_version=True
            ).exclude(pk=self.instance.pk).update(is_current_version=False)
        return cleaned_data


class ManagerForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "description",
            "category",
            "is_published",
        ]

categories/views.py
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
)
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from categories.models.product import Product
from categories.models.category import Category
from categories.models.version import Version
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from categories.forms import ProductForm, VersionForm, ManagerForm
from django.forms.models import inlineformset_factory


class ProductListView(ListView):
    model = Product
    context_object_name = "object_list"

    def get_queryset(self):
        category_id = self.request.GET.get("category")

        # Начинаем с полного списка опубликованных продуктов
        queryset = Product.objects.filter(is_published=True).prefetch_related(
            "versions"
        )

        # Фильтрация по категории, если она указана
        if category_id:
            queryset = queryset.filter(category_id=category_id)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("categories:product_store")

    def form_valid(self, form):
        # Устанавливаем автора на текущего пользователя
        form.instance.author = self.request.user
        return super().form_valid(form)


class ProductDetailView(DetailView):
    model = Product


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    model = Product
    success_url = reverse_lazy("categories:product_store")
    # permission_required = "categories.change_product"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        if self.get_object().author == user or user.has_perm(
            "categories.change_product"
        ):
            VersionFormset = inlineformset_factory(
                Product,
                Version,
                form=VersionForm,
                extra=1,
                can_delete=True,
            )

            if self.request.POST:
                context["formset"] = VersionFormset(
                    self.request.POST, instance=self.object
                )
            else:
                context["formset"] = VersionFormset(instance=self.object)

        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)  # Сохраняем основной объект
        formset = self.get_context_data()["formset"]

        if formset.is_valid():
            self.object.save()  # Сохраняем основной объект
            formset.instance = self.object  # Привязываем версии к объекту
            formset.save()  # Сохраняем версии
            return super().form_valid(form)  # Перенаправляем после успешного сохранения
        else:
            return self.form_invalid(form)  # Если форма не валидна, возвращаем ошибки

    def test_func(self):
        user = self.request.user
        return self.get_object().author == user or any(
            [
                user.has_perm("categories.can_change_product_categories"),
                user.has_perm("categories.can_set_product_published"),
                user.has_perm("categories.can_change_description"),
            ]
        )

    def get_form_class(self):
        user = self.request.user
        if self.get_object().author == user or user.has_perm(
            "categories.change_product"
        ):
            return ProductForm
        else:
            return ManagerForm

categories/templates/categories/includes/app_menu.html
<nav class="navbar navbar-expand-md bg-dark sticky-top border-bottom" data-bs-theme="dark">
    <div class="container">
        <a class="navbar-brand d-md-none" href="#">
            <svg class="bi" width="24" height="24">
                <use xlink:href="#aperture"/>
            </svg>
            Aperture
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvas"
                aria-controls="offcanvas" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvas" aria-labelledby="offcanvasLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasLabel">Aperture</h5>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav flex-grow-1 justify-content-between">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="categoriesDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Все товары
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="categoriesDropdown">
                            <li><a class="dropdown-item" href="{% url 'categories:product_store' %}">Все продукты</a></li>
                            {% for category in categories %}
                                <li><a class="dropdown-item" href="{% url 'categories:product_store' %}?category={{ category.id }}">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'categories:product_form' %}">Создание продукта</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog_store:blogpost_form' %}">Добавить Блог</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog_store:blogpost_list' %}">Блоги</a></li>

<li class="nav-item">
    {% if user.is_authenticated %}
        <form action="{% url 'users:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="nav-link btn btn-link">Выход</button>
        </form>
    {% else %}
        <a class="nav-link" href="{% url 'users:login' %}">Вход</a>
        <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
    {% endif %}
</li>
                    <li class="nav-item"><a class="nav-link" href="#">
                        <svg class="bi" width="24" height="24">
                            <use xlink:href="#cart"/>
                        </svg>
                    </a></li>
                </ul>
            </div>
        </div>
    </div>
</nav>