blog_store/urls.py
from django.urls import path
from blog_store.views import (
    BlogCreateView,
    BlogListView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
    activity,
)

app_name = "blog_store"

urlpatterns = [
    path("blog_create", BlogCreateView.as_view(), name="blogpost_form"),
    path("blogs", BlogListView.as_view(), name="blogpost_list"),
    path(
        "blogs/<int:pk>-<slug:slug>", BlogDetailView.as_view(), name="blogpost_detail"
    ),
    path(
        "blog_update/<int:pk>-<slug:slug>",
        BlogUpdateView.as_view(),
        name="blogpost_form",
    ),
    path(
        "delete_blog/<int:pk>-<slug:slug>",
        BlogDeleteView.as_view(),
        name="blogpost_delete",
    ),
    path("blogs/activity/<int:pk>-<slug:slug>", activity, name="blogpost_activity"),
]


# другие urlpatterns

online_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("categories.urls", namespace="categories")),
    path("blog_store/", include("blog_store.urls", namespace="blog_store")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView, PasswordResetDoneView, PasswordResetConfirmView
from django.views.generic import TemplateView

from users.apps import UsersConfig
from users.views import RegisterUser, VerifyEmailView, password_reset_view

app_name = UsersConfig.name





urlpatterns = [
    path("logout/", LogoutView.as_view(), name="logout"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("register/", RegisterUser.as_view(), name="register"),
    path('verify_email/<str:token>/', VerifyEmailView.as_view(), name='verify_email'),
    path('email_verified/', TemplateView.as_view(template_name='users/email_verified.html'), name='email_verified'),
    path('invalid_token/', TemplateView.as_view(template_name='users/invalid_token.html'), name='invalid_token'),
    path('register/message_post/', TemplateView.as_view(template_name='users/message_post.html'), name='message_post'),
    path('login/password_reset/', password_reset_view, name='password_reset')
]

blog_store/models.py
from django.db import models
import pytils.translit

# Create your models here.
NULLABLE = {"blank": True, "null": True}

from django.db import models
from django.utils.text import slugify


class BlogPost(models.Model):
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    slug = models.SlugField(verbose_name="URL", unique=True)
    content = models.TextField(verbose_name="Содержание заголовка")
    preview = models.ImageField(
        upload_to="image_blog", verbose_name="Изображение", **NULLABLE
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="дата создания")
    is_published = models.BooleanField(default=True, verbose_name="Активно")
    views_count = models.PositiveIntegerField(
        default=0, verbose_name="Коллличество просмотров"
    )

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = pytils.translit.slugify(self.title)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "блог"
        verbose_name_plural = "блоги"

blog_store/forms.py
from django import forms
from .models import BlogPost


class BlogBaseForm:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class BlogForms(BlogBaseForm, forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = [
            "title",
            "content",
            "preview",
        ]

blog_store/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)
from blog_store.models import BlogPost
from .forms import BlogForms


class BlogCreateView(CreateView):
    model = BlogPost
    success_url = reverse_lazy("blog_store:blogpost_list")
    form_class = BlogForms
    # form_valid()
    # обработка валидации формы, используется в контроллерах
    # form_valid()обработка валидации формы, используется в контроллерах
    # form_invalid()обработка невалидной формы, используется в контроллерах
    # CreateView и UpdateView


class BlogListView(ListView):
    model = BlogPost
    # get_paginate_by()
    # получение количества записей для постраничного вывода,
    # используется только в контроллере ListView.


class BlogDetailView(DetailView):
    model = BlogPost

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object

    # get_queryset()получение запроса для формирования данных, используется в каждом контроллере.
    # get_context_data()получение контекста для формирования ответа,
    # который будет рендериться из шаблона, используется в каждом контроллере


class BlogUpdateView(UpdateView):
    model = BlogPost
    form_class = BlogForms
    success_url = reverse_lazy("blog_store:blogpost_list")

    # form_valid()
    # обработка валидации формы, используется в контроллерах
    # form_valid()обработка валидации формы, используется в контроллерах
    # form_invalid()обработка невалидной формы, используется в контроллерах
    # CreateView и UpdateView

    def get_object(self, queryset=None):  # получение запроса для формирования данных,
        # используется в каждом контроллере.
        pk = self.kwargs.get("pk")
        slug = self.kwargs.get("slug")
        return get_object_or_404(self.model, pk=pk, slug=slug)

    # get_queryset()получение запроса для формирования данных, используется в каждом контроллере.
    # get_context_data()получение контекста для формирования ответа,
    # который будет рендериться из шаблона, используется в каждом контроллере


class BlogDeleteView(DeleteView):
    model = BlogPost
    success_url = reverse_lazy("blog_store:blogpost_list")

    # get_queryset()получение запроса для формирования данных, используется в каждом контроллере.
    # get_context_data()получение контекста для формирования ответа,
    # который будет рендериться из шаблона, используется в каждом контроллере


def activity(request, pk, slug):
    blogpost = get_object_or_404(BlogPost, pk=pk, slug=slug)
    if blogpost.is_published:
        blogpost.is_published = False
    else:
        blogpost.is_published = True

    blogpost.save()

    return redirect(reverse_lazy("blog_store:blogpost_list"))

blog_store/templates/blog_store/blogpost_confirm_delete.html
{% extends 'categories/base.html' %}
{% load tags_template %}

{% block content %}
  <h1>Удаление блог-поста</h1>
  <p>Вы действительно хотите удалить этот блог-пост?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Да, удалить</button>
    <a href="{% url 'blog_store:blogpost_list' %}" class="btn btn-secondary">Отмена</a>
  </form>
{% endblock %}

blog_store/templates/blog_store/blogpost_detail.html
{%extends 'categories/base.html'%}
{%block content%}
{%load tags_template%}

<div class="container">
    <h1>{{ object.title }}</h1>
    <img src="{{ object.preview|media_filter }}" class="card-image">
    <p>{{ object.content }}</p>
    <p>Статус: {{ object.is_published }}</p>
    <p>Кол-во просмотров: {{ object.views_count }}</p>
    <p>Дата создания: {{ object.created_at }}</p>
</div>

{%endblock%}

blog_store/templates/blog_store/blogpost_form.html
{% extends 'categories/base.html' %}
{% block content %}
  <div class="card shadow-sm">
    <div class="card-body">
      <form class="row g-3" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="col-12">
          <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

blog_store/templates/blog_store/blogpost_list.html
{% extends 'categories/base.html' %}
{% load tags_template %}

{% block content %}
  <h1>Список блог-постов</h1>
  <div class="row">
    {% for post in object_list %}
      <div class="col-md-6">
        <div class="card">
          <h2>{{ post.title }}</h2>
          <img src="{{ post.preview|media_filter }}" class="card-image">
          <p>{{ post.content }}</p>
          <p>{{ post.created_at|date:"d.m.Y" }}</p>
          <div class="d-flex justify-content-between">
            <a href="{% url 'blog_store:blogpost_detail' post.pk post.slug%}" class="btn btn-primary">Перейти</a>
            <a href="{% url 'blog_store:blogpost_form' post.pk post.slug %}" class="btn btn-success">Редактировать</a>
            {% if post.is_published %}
              <a href="{% url 'blog_store:blogpost_activity' pk=post.pk slug=post.slug %}" class="btn btn-warning">Деактивировать</a>
            {% else %}
              <a href="{% url 'blog_store:blogpost_activity' post.pk post.slug %}" class="btn btn-secondary">Активировать</a>
            {% endif %}
            <a href="{% url 'blog_store:blogpost_delete' post.pk post.slug %}" class="btn btn-danger">Удалить</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}