categories/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from categories.apps import CategoriesConfig  # Импорт для формирования ключа

from .views import (
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
)

app_name = CategoriesConfig.name

urlpatterns = [
    path("", ProductListView.as_view(), name="product_store"),  # Список продуктов
    path(
        "contact/", ProductCreateView.as_view(), name="product_form"
    ),  # Форма создания продукта
    path(
        "product_store/product_detail/<int:pk>/",
        cache_page(60)(ProductDetailView.as_view()),
        name="product_detail",
    ),
    path(
        "product_store/product_update/<int:pk>/",
        ProductUpdateView.as_view(),
        name="update_forms",
    ),  # Обновление продукта
]

online_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("categories.urls", namespace="categories")),
    path("blog_store/", include("blog_store.urls", namespace="blog_store")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView, PasswordResetDoneView, PasswordResetConfirmView
from django.views.generic import TemplateView

from users.apps import UsersConfig
from users.views import RegisterUser, VerifyEmailView, password_reset_view

app_name = UsersConfig.name





urlpatterns = [
    path("logout/", LogoutView.as_view(), name="logout"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("register/", RegisterUser.as_view(), name="register"),
    path('verify_email/<str:token>/', VerifyEmailView.as_view(), name='verify_email'),
    path('email_verified/', TemplateView.as_view(template_name='users/email_verified.html'), name='email_verified'),
    path('invalid_token/', TemplateView.as_view(template_name='users/invalid_token.html'), name='invalid_token'),
    path('register/message_post/', TemplateView.as_view(template_name='users/message_post.html'), name='message_post'),
    path('login/password_reset/', password_reset_view, name='password_reset')
]

categories/models/category.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"

categories/models/product.py
from django.db import models
from users.models import User

# Create your models here.
NULLABLE = {"blank": True, "null": True}  # делает не обязательным
# заполнения поля
# если не заполнить
# то оно является обязательным для заполнения


# формирует в бд таблицы
class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="Наименование")  # Наименование
    description = models.TextField(verbose_name="Описание")  # Описание
    image_product = models.ImageField(
        verbose_name="Изображение товара",
        upload_to="image_product/",
        name="image_product",
        **NULLABLE
    )  # Изображение

    category = models.ForeignKey(
        "Category", on_delete=models.CASCADE, verbose_name="Категории спорта"
    )  # Категория здесь идёт связь
    # таблиц
    # Продуктов и категории
    price_per_purchase = models.IntegerField(
        verbose_name="Устанока цены"
    )  # Цена за покупку
    date_of_creation = models.DateTimeField(
        auto_now_add=True
    )  # Дата создания (записи в БД)
    date_of_last_change = models.DateTimeField(
        auto_now=True
    )  # Дата последнего изменения (записи в БД)
    # manufactured_at = models.DateField()  # Дата производства продукта

    author = models.ForeignKey(User, on_delete=models.SET_NULL, **NULLABLE)
    is_published = models.BooleanField(
        default=False, verbose_name="признак публиукации"
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"
        permissions = [
            ("can_change_product_categories", "Может изменять название Категории"),
            ("can_set_product_published", "Может изменять статус публикации"),
            ("can_change_description", "может менять описание любого продукта"),
        ]

categories/models/version.py
from django.db import models


class Version(models.Model):

    product = models.ForeignKey(
        "Product", on_delete=models.CASCADE, related_name="versions"
    )
    number_version = models.CharField(max_length=100, verbose_name="номер версии")
    name_version = models.CharField(max_length=100, verbose_name="название версии")
    is_current_version = models.BooleanField(
        default=False, verbose_name="Признак текущей версии"
    )

    def __str__(self):
        return f"{self.name_version}, {self.number_version}"

    class Meta:
        verbose_name = "версия продукта"
        verbose_name_plural = "версии продуктов"

categories/forms.py
from django import forms
from categories.models.product import Product
from categories.models.version import Version
from categories.list_config_name.config_name import FORBIDDEN_WORDS


class BootstrapForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({"class": "form-control"})


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "name",
            "description",
            "image_product",
            "category",
            "price_per_purchase",
            "is_published",
        ]

    def clean_name(self):
        name = self.cleaned_data["name"].lower()
        for forbidden_word in FORBIDDEN_WORDS:
            if forbidden_word in name:
                raise forms.ValidationError("Пожалуйста, измените название.")
        return name


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ["product", "name_version", "number_version", "is_current_version"]

    def clean(self):
        cleaned_data = super().clean()
        is_active = cleaned_data.get("is_current_version")
        if is_active and self.instance.product:
            Version.objects.filter(
                product=self.instance.product, is_current_version=True
            ).exclude(pk=self.instance.pk).update(is_current_version=False)
        return cleaned_data


class ManagerForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "description",
            "category",
            "is_published",
        ]

categories/views.py
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
)
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from categories.models.product import Product
from categories.models.category import Category
from categories.models.version import Version
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from categories.forms import ProductForm, VersionForm, ManagerForm
from django.forms.models import inlineformset_factory


class ProductListView(ListView):
    model = Product
    context_object_name = "object_list"

    def get_queryset(self):
        category_id = self.request.GET.get("category")

        # Начинаем с полного списка опубликованных продуктов
        queryset = Product.objects.filter(is_published=True).prefetch_related(
            "versions"
        )

        # Фильтрация по категории, если она указана
        if category_id:
            queryset = queryset.filter(category_id=category_id)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("categories:product_store")

    def form_valid(self, form):
        # Устанавливаем автора на текущего пользователя
        form.instance.author = self.request.user
        return super().form_valid(form)


class ProductDetailView(DetailView):
    model = Product


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    model = Product
    success_url = reverse_lazy("categories:product_store")
    # permission_required = "categories.change_product"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        if self.get_object().author == user or user.has_perm(
            "categories.change_product"
        ):
            VersionFormset = inlineformset_factory(
                Product,
                Version,
                form=VersionForm,
                extra=1,
                can_delete=True,
            )

            if self.request.POST:
                context["formset"] = VersionFormset(
                    self.request.POST, instance=self.object
                )
            else:
                context["formset"] = VersionFormset(instance=self.object)

        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)  # Сохраняем основной объект
        formset = self.get_context_data()["formset"]

        if formset.is_valid():
            self.object.save()  # Сохраняем основной объект
            formset.instance = self.object  # Привязываем версии к объекту
            formset.save()  # Сохраняем версии
            return super().form_valid(form)  # Перенаправляем после успешного сохранения
        else:
            return self.form_invalid(form)  # Если форма не валидна, возвращаем ошибки

    def test_func(self):
        user = self.request.user
        return self.get_object().author == user or any(
            [
                user.has_perm("categories.can_change_product_categories"),
                user.has_perm("categories.can_set_product_published"),
                user.has_perm("categories.can_change_description"),
            ]
        )

    def get_form_class(self):
        user = self.request.user
        if self.get_object().author == user or user.has_perm(
            "categories.change_product"
        ):
            return ProductForm
        else:
            return ManagerForm

categories/templates/categories/base.html
{%load static%}

<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Product example · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/product/">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/product.css'%}" rel="stylesheet">
</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="aperture" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
            stroke-width="2" viewBox="0 0 24 24">
        <circle cx="12" cy="12" r="10"/>
        <path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/>
    </symbol>
    <symbol id="cart" viewBox="0 0 16 16">
        <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </symbol>
    <symbol id="chevron-right" viewBox="0 0 16 16">
        <path fill-rule="evenodd"
              d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
    </symbol>
</svg>
    <div>
        {% include 'categories/includes/app_menu.html' %}

    </div>
<main>
    <main>
        {% block content %}
        {%endblock%}
    </main>
</main>

<footer class="container py-5">
    <div class="row">
        <div class="col-12 col-md">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor"
                 stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img"
                 viewBox="0 0 24 24"><title>Product</title>
                <circle cx="12" cy="12" r="10"/>
                <path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/>
            </svg>
            <small class="d-block mb-3 text-body-secondary">&copy; 2017–2024</small>

<script src="{%static 'js/bootstrap.bundle.min.js'%}" crossorigin="anonymous"></script>

categories/templates/categories/product_detail.html
{% extends 'categories/base.html' %}
{%block content%}
{%load tags_tags%}

<h1>{{ object.name }}</h1>
<img src="{{ product.image_product|media_filter }}" class="card-image">
<p>{{ object.description }}</p>
<p>Цена: {{ object.price_per_purchase }}</p>
<p>Категория: {{ object.category.name }}</p>
<p>Дата создания: {{object.date_of_creation }}</p>
<p>Дата изменения: {{ object.date_of_last_change }}</p>
{%endblock%}

categories/templates/categories/product_form.html
{% extends 'categories/base.html' %}
{% block content %}
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card shadow-lg">
        <div class="card-header bg-primary text-white">
          <h4 class="mb-0">Создание Продукта</h4>
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            {{ formset.management_form }}
            {% for form in formset.forms %}
              {{ form.as_p }}
            {% endfor %}
            <div class="d-grid gap-2 mt-3">
              <button type="submit" class="btn btn-primary btn-lg">Сохранить версии и редактировать</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

categories/templates/categories/product_list.html
{% extends 'categories/base.html' %}
{% block content %}
{% load tags_tags %}
<div class="row">
    {% for prod in object_list %}
    <div class="col-md-6">
        <div class="card shadow-sm">
            <img src="{{ prod.image_product | media_filter }}" class="card-image">
            <div class="card-body">
                <p class="card-text">{{ prod.name }}</p>
                <p class="card-text">{{ prod.description|truncatechars:100 }} | Автор продукта: {% if prod.author %}{{ prod.author }}{% else %}Неизвестен{% endif %}</p>

                <h5>Версии продукта:</h5>
                <ul>
                    {% for version in prod.versions.all %}
                        <li>
    <strong>Номер версии - {{ version.name_version }}</strong> Название версии - {{ version.number_version }}) -
    {% if version.is_current_version %}Активна{% else %}Неактивна{% endif %}
</li>
                    {% empty %}
                        <li>Нет доступных версий.</li>
                    {% endfor %}
                </ul>

                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'categories:update_forms' prod.id %}" class="btn btn-success me-2">Редактировать</a>
                        <a type="button" class="btn btn-primary" onclick="window.location.href='{% url 'categories:product_detail' prod.id %}'">О товаре</a>
                    </div>
                    <small class="text-body-secondary">Цена: {{ prod.price_per_purchase }}</small>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}